[package]
name = "eth_gas_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.19"
megalodon = "0.8.9"
reqwest = "0.11.18"
serde = "1.0.179"
tokio = "1.29.1"
url = "2.4.0"
